### ISSUE TITLE
ModuleNotFoundError: No module named 'allelefreq' .

### ISSUE THREAD

**Issue by emmaevonk** [stevemussmann/fastStructure3#1]
When I run fastSTRUCTURE3 I get a ModuleNotFoundError. What is the cause and how can I fix this? The error is as follows:

Traceback (most recent call last):
  File "~/fastStructure3/structure.py", line 4, in <module>
    import fastStructure
  File "fastStructure.pyx", line 2, in init fastStructure
    import numpy as np
  File "admixprop.pyx", line 1, in init admixprop
ModuleNotFoundError: No module named 'allelefreq'

**Comment by stevemussmann** [comment]
I've also run into this problem with it not finding some of the faststructure modules on certain systems. Unfortunately, I don't have a solution yet but I will keep looking into it as I have time.

**Comment by emmaevonk** [comment]
I fixed the issue, apparently it was a problem with Cython. When I used Python 3.9 I couldn't get the right version of Cython, so I downgraded it to Python 3.6 and Cython 0.26 and it works now :)
